### ISSUE TITLE
Use anchors, not buttons, for linking to download content

### ISSUE THREAD

**Issue by wbazant** [PRIDE-Archive/pride-web#101]
I tried to get the 2.5 GB dataset from 
http://wwwdev.ebi.ac.uk/pride/dataset/PXD010342

by copying the link and looking for it in the EBI FTP. I'd also do it with an outside service - I would rather download things through `wget` than my browser when the files are so big.

This issue suggest anchor tags instead of buttons to implement download links. You can still make an anchor tag look like a button if you want to.

It will then support what I wanted to do, and it's also good for accessibility: press tab a few times on the site to see that it is hard to can navigate without a mouse. A screen reader will also read out just the links.

@ypriverol  do close if it's a bad issue or if you don't want this kind of feedback here!

**Comment by wbazant** [comment]
For a more powerful solution: consider making `http://wwwdev.ebi.ac.uk/pride/dataset/PXD010342.xml` a thing ( like ENA or UniProt), or even `http://wwwdev.ebi.ac.uk/pride/dataset/PXD010342.json`.

**Comment by ypriverol** [comment]
@shabai517 this is a great feature. The idea would be that users can add only an xml extension or json at the end of the project and that will give you the representation.
