### ISSUE TITLE
The profile page should be refined 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#104]
@shabai517 The profile page still contains a lot of data without fill. Please give priority to put the current data from the database into the profile.

**Comment by shabai517** [comment]
I think the user information still can not be retrieved by our api...The only thing I could do now is to remove the content in the UI temporally until the api works.

**Comment by ypriverol** [comment]
Abonado said that this is working already

**Comment by shabai517** [comment]
Fixed and check.
