### ISSUE TITLE
plot api needs to be moved onto wwwdev

### ISSUE THREAD

**Issue by shabai517** [PRIDE-Archive/pride-web#107]
http://wwwdev.ebi.ac.uk/pride/ws/archive/stats/SUBMISSIONS_PER_COUNTRY 

http://wwwdev.ebi.ac.uk/pride/ws/archive/stats/SUBMISSIONS_PER_CATEGORIES

These two apis works fine on "www.ebi.ac.uk/pride/ws/archive/v2" which is for production.

Currently, I am doing the test on wwwdev. So these two apis does not work anymore.

**Comment by chakrabandla** [comment]
new URLS: 
http://wwwdev.ebi.ac.uk/pride/ws/archive/v2/stats/SUBMISSIONS_PER_CATEGORIES
http://wwwdev.ebi.ac.uk/pride/ws/archive/v2/stats/SUBMISSIONS_PER_COUNTRY
