### ISSUE TITLE
archive search api problem.

### ISSUE THREAD

**Issue by shabai517** [PRIDE-Archive/pride-web#108]
http://wwwdev.ebi.ac.uk/pride/ws/archive/v2/search/projects?keyword=Homo+sapiens+human&filter=organisms_part_facet%3DBrain&sortConditions=accession&page=0&pageSize=20&dateGap=%2B1YEAR&sortDirection=DESC

This api with all the following queries does not work well.

**Comment by ypriverol** [comment]
What means, do not work well?

**Comment by shabai517** [comment]
The results are not correct:

1. The results are same with the filter "organisms_part_facet + Brain" or without this filter. As the comments from Suresh, he said this filter should give different results.
2. The sortCondition filter with accession also makes no change of the results. But it should change the order according to the accession.

All the test are done in front end, the relative queries have been sent to back-end. However, the api does not give an expected results.

Before checking the back-end api, could we check if the method of attaching the queries in the api are correct or not?

**Comment by ypriverol** [comment]
@chakrabandla can you take a look to this?

**Comment by chakrabandla** [comment]
@shabai517 use '==' in filter instead of '='
