### ISSUE TITLE
After clicking similar datasets the contacts accumulate

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#110]
- When I click on several of “similar studies” consecutively the display of the contacts and reference changes (and accumulates) in the target datasets. There still seems to be a nasty bug there. This really needs to be fixed. It is difficult to explain what happens without showing it “live”. See attached screenshot (this one is updated).

Reported by @javizca 

![image](https://user-images.githubusercontent.com/52113/62858638-b8337b80-bcf2-11e9-89fc-de780ae57b5d.png)

**Comment by shabai517** [comment]
Fixed and plz check.
