### ISSUE TITLE
The dataset word is attached to the Keywords

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#111]
In some of the tags the word “dataset” is duplicated, e.g. “Metaproteomics dataset dataset”, “Technical dataset dataset”, “Biomedical dataset dataset”, and maybe others.

Reported by @javizca 

![image](https://user-images.githubusercontent.com/52113/62858691-dbf6c180-bcf2-11e9-9621-f856b184c2a0.png)

**Comment by shabai517** [comment]
needs more explain

**Comment by ypriverol** [comment]
Fixed in the following commit https://github.com/PRIDE-Archive/pride-web/commit/659b9c3869dfc4de7e5071b693961f0df2db26d1
