### ISSUE TITLE
Property values in dataset page should be links to search

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#116]
Property Values in the dataset CAN BE Links to the Search page: 

Comment from @javizca: 

Inside a given dataset, when in the “Properties” panel, one see some text underlined, and for me it means a link to the outside world. But there is no link there. In the current PRIDE, we link to a search with this particular term (e.g. a modification such as “monohydroxylated residue”). In the previous PRIDE, it links to OLS. There are some particular terms there like the project tags, that in my view should definitely link to a list of the projects (e.g. “Human Proteome Project”), because that should be expected in that case.

**Comment by shabai517** [comment]
Needs more explain

**Comment by shabai517** [comment]
Fixed.
