### ISSUE TITLE
We need to add as facet the COMPLETE and PARTIAL Submissions

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#119]
It is not possible to filter by complete/partial submissions. For that, we need to be sure that these categories are a facet in the backend.

**Comment by chakrabandla** [comment]
@ypriverol @shabai517  API can now fetch the submission_type facet. `{"field":"project_submission_type","values":[{"value":"partial","count":33},{"value":"complete","count":6}]}`

**Comment by ypriverol** [comment]
@shabai517 can you add this field to the facet in the Web.

**Comment by ypriverol** [comment]
Done.
