### ISSUE TITLE
The PSM can't be found for this particular peptide 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#125]
In the project http://wwwdev.ebi.ac.uk/pride/dataset/PXD008150/Molecules If I select the first Protein and unique peptide `MIEQLKR`, I'm not able to select the PSM.

**Comment by ypriverol** [comment]
Another example here: 

http://wwwdev.ebi.ac.uk/pride/dataset/PXD008150/Molecules?reportedAccession=Q16186&assayAccession=82281&sortConditions=projectAccession&sortDirection=DESC&page=0&pageSize=20

![Screen Shot 2019-09-20 at 11 54 31](https://user-images.githubusercontent.com/52113/65321966-80471000-db9d-11e9-8ac9-facd2a8760dc.png)

**Comment by shabai517** [comment]
The peptide evidence accession is not in the database --PXD008150:82281:Q8WZ74:MIEQLKR Contact pride support: pride-support@ebi.ac.uk

**Comment by ypriverol** [comment]
Done.
