### ISSUE TITLE
Reply the user type after login successfully

### ISSUE THREAD

**Issue by shabai517** [PRIDE-Archive/pride-web#131]
In the current login API '/getAAPToken', only the token is replied. 

However, as different users should have different rights in terms of the projects, the front-end needs to know the user type to disable or enable some button functions.

The reply may be like this {'type':'reviewer'; 'token':'XXXXXXX'}

**Comment by chakrabandla** [comment]
@shabai517 you can use this https://wwwdev.ebi.ac.uk/pride/ws/archive/v2/user/view-profile

**Comment by chakrabandla** [comment]
I am closing this.
