### ISSUE TITLE
Some minor spelling problems

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#135]
- In the "log-in” screen, it should be “Forgotten password” and not “Forget password”. 

It should be “Public datasets”, not “Public data”. 

- The same is applicable to “Private data”. 

- Remove Delete. 

- In the personal profile, it should be “ORCID” (all in capital letters).

-When I log-out, it goes by default to the PRIDE annotation system page (http://wwwdev.ebi.ac.uk/pride/annotation). It should go to PRIDE Archive.

**Comment by shabai517** [comment]
Fixed and please check

**Comment by ypriverol** [comment]
Done.
