### ISSUE TITLE
URL to FTP project should be available

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#168]
@shabai517 It would be great to have in the file table a button at the end to link to the FTP of the project. Like: 

<img width="1232" alt="Screen Shot 2019-12-03 at 07 47 39" src="https://user-images.githubusercontent.com/52113/70030498-41700600-15a1-11ea-9054-9a4755995ee4.png">

**Comment by shabai517** [comment]
I need the download link of FTP.
