### ISSUE TITLE
Path to download PRIDE Inspector

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/pride-web#178]
I cannot find where  download PRIDE Inspector in the new website. In https://www.ebi.ac.uk/pride/markdownpage/prideinspector it should appear a link to https://github.com/PRIDE-Toolsuite/pride-inspector.

**Comment by ypriverol** [comment]
Thanks for reporting this.

**Comment by ypriverol** [comment]
Solve in this PR https://github.com/PRIDE-Archive/pride-web/pull/181
