### ISSUE TITLE
Misleading behavior in archive search

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-web#191]
<img width="757" alt="Screen Shot 2019-12-13 at 1 03 42 PM" src="https://user-images.githubusercontent.com/5387193/70802326-1491cf00-1da9-11ea-9579-fc453944f237.png">

In the example, I am searching a dataset with PXD016700 accession. A popup/automatic textbox shows "No matching data", however if you click the search button, then you can see data.

**Comment by ypriverol** [comment]
This is not a problem in the Web interface is more a problem in the backend suggestion system. @selvaebi can you take a look why submission accession are not included in the suggestion system.

**Comment by selvaebi** [comment]
Done
