### ISSUE TITLE
implement password reset page

### ISSUE THREAD

**Issue by chakrabandla** [PRIDE-Archive/pride-web#195]

**Comment by chakrabandla** [comment]
Webpage path : /forgotpassword

**Comment by chakrabandla** [comment]
tried to release to DEV & PROD but the APP team doesn't allow www.ebi.ac.uk & wwwdev.ebi.ac.uk doamins.. so I asked them to allow those.. will release again after they fix it

**Comment by ypriverol** [comment]
@chakrabandla and @shabai517 is this task done.

**Comment by chakrabandla** [comment]
yeah done..closing
