### ISSUE TITLE
Update File formats documentation in PRIDE website

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/pride-web#209]
The MaxQuant datasets are becoming more and more abundant, it could be good to improve the documentation about the file formats, since it is not very clear and they are rather different to the others.

See the site:
https://www.ebi.ac.uk/pride/markdownpage/pridefileformats

In the PRIDE FAQs website (https://www.ebi.ac.uk/pride/help/archive/faq#MaxQuant) we can find more info about the MaxQuant files, this info is still valid, so we can use it to update the File formats documentation.

In summary we can include for example:

For the SEARCH file: 
If you are using MaxQuant (version 1.3.0.5 or more recent) there is a txt folder generated and by default you can just zip this text folder and upload as search/identification file.
If this is complicated we would recommend uploading the following particular text output files: peptides.txt, modifiedPeptides.txt, proteinGroups.txt, msms.txt, parameters.txt and your Experimental Design Template file saved as a tab separated file.

For PEAK file:
There is a folder, usually entitled 'Andromeda', containing the .apl peak list files you can compress in a zip file and annotate it as a PEAK file as it helps with PSM recovery.

**Comment by ypriverol** [comment]
@davco6 feel free to add the section for maxquant and update the documentation. Please do a Pull Request and I will review it.

**Comment by ypriverol** [comment]
This has been done.
