### ISSUE TITLE
Project Description modification error

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/pride-web#213]
I used PRIDE Archive Curation System to modify the Project Description from the dataset PXD019008 . After that the user complains due to the description is not complete, it seems that although in http://ves-ebi-4b.ebi.ac.uk:8080/pride/curation/project/PXD019008 it shows the complete version, in the user account(or reviewer) it is not complete. Might be a space limit issue? The total count of character is about 1050 way lower than the allowed shown in PX submission too (5000).

**Comment by ypriverol** [comment]
@davco6 is this problem solved? we should use the API I think?

**Comment by davco6** [comment]
Yes, it is solved
