### ISSUE TITLE
Move pride documentation to separate repo

### ISSUE THREAD

**Issue by chakrabandla** [PRIDE-Archive/pride-web#222]
documentation can be fetched from different github repo
we don't have to make a release for updating documentation.

**Comment by ypriverol** [comment]
This would be cool. However, the way the documentation is built is taking the documentation and generating the HTML. I don't see how moving to another repo would help unless we change all the approaches. In any case I don't think the documentation should change often.

**Comment by chakrabandla** [comment]
>  This would be cool. However, the way the documentation is built is taking the documentation and generating the HTML. I don't see how moving to another repo would help unless we change all the approaches. 

while generating html, instead of reading the documentation from local file , it can be fetched from URL & generate html. 
Is that not possible. I feel it can be done & it just gives more flexibility
