### ISSUE TITLE
FTP Download TAB is hidden behind the SEARCH TAB

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-web#224]
<img width="916" alt="Screenshot 2020-09-01 at 15 37 52" src="https://user-images.githubusercontent.com/38948179/91878041-afec0c80-ec76-11ea-8df9-1ec235769c6d.png">
<img width="1354" alt="Screenshot 2020-09-01 at 15 38 39" src="https://user-images.githubusercontent.com/38948179/91878050-b24e6680-ec76-11ea-8674-77ee3d013cc8.png">

**Comment by ypriverol** [comment]
Fixed.
