### ISSUE TITLE
Implementation of the similar datasets panel for each dataset. 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#23]

**Comment by shabai517** [comment]
@ypriverol The panel should be checked and decide if this issue should be closed.

**Comment by shabai517** [comment]
Finished. Please check @ypriverol

**Comment by ypriverol** [comment]
Thanks @shabai517 . It looks great, One minor thing, If I click the title of the Project in the similar, it should go to the Project page.

**Comment by shabai517** [comment]
@ypriverol  Fixed. Please check
