### ISSUE TITLE
Aspera information is missing in the documentation

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-web#242]
Probably, with the new vue 3.0 release, this page is missing:
http://www.ebi.ac.uk/pride/help/archive/aspera

**Comment by ypriverol** [comment]
Please, @sureshhewabi take the lead here.

**Comment by sureshhewabi** [comment]
https://www.ebi.ac.uk/pride/markdown/submitdatapage/files/Submission_Tutorial.pdf

**Comment by ypriverol** [comment]
This should be converted to Aspera page.

**Comment by sureshhewabi** [comment]
yes, it had some depicted informations. I will prepare it correctly and put it into a page

**Comment by ypriverol** [comment]
This has been recently solved.
