### ISSUE TITLE
Separate pubmed & doi fileds in 'publish project' form

### ISSUE THREAD

**Issue by chakrabandla** [PRIDE-Archive/pride-web#247]
In 'publish project' form pubmed/doi filed is not mandatory anymore. So, it's better to separate those fields.

The current drop down is causing confusion to users.

**Comment by javizca** [comment]
Just for clarification purposes. 
DOI or PMID need to be mandatory for non-registered users (anonymous)
For registered ones, it should not be mandatory (of course, for their own datasets only)

**Comment by chakrabandla** [comment]
Is there an option to request publication of other's dataset from pride web?

**Comment by javizca** [comment]
Yes,

see e.g. https://www.ebi.ac.uk/pride/archive/projects/PXD022001/publish 

People can request this anonymously (for instance, when reading a paper, and the corresponding  dataset has not been made yet public by the authors of the paper)

**Comment by chakrabandla** [comment]
OK.. Just curious, how do user navigate to that page? Do they have have to know the URL ?
I couldn't figure out how to navigate from web :)

**Comment by chakrabandla** [comment]
> Yes,
> 
> see e.g. https://www.ebi.ac.uk/pride/archive/projects/PXD022001/publish
> 
> People can request this anonymously (for instance, when reading a paper, and the corresponding dataset has not been made yet public by the authors of the paper)

Just checked about this functionality & can confirm that this is not currently supported

**Comment by javizca** [comment]
this page  is available from ProteomeCentral, when a PRIDE dataset is not public there, for instance:

http://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD022001

We added that link there to facilitate the reporting of datasets that should be made public
I think it is used relatively often
