### ISSUE TITLE
PRIDE Web SEO information

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#248]
@shabai517 This is my solution to the problem of google indexing. 

First problem header meta values are missing for projects: 

Here are our meta values of Project PXD015689: 

![Screen Shot 2021-02-18 at 10 42 41](https://user-images.githubusercontent.com/52113/108345540-4cc74580-71d6-11eb-886c-f1c6cd743ca9.png)

The meta values `description` and `title`  are missing. 

You can check in OmicsDI how that looks (URL - https://www.omicsdi.org/dataset/pride/PXD015689): 

![Screen Shot 2021-02-18 at 10 43 03](https://user-images.githubusercontent.com/52113/108345475-3620ee80-71d6-11eb-986a-abbfb48cfcec.png)

In addition, we should provide Schema.org representation for each dataset using the following guidelines https://developers.google.com/search/docs/data-types/dataset .

**Comment by ypriverol** [comment]
Here is the example of OmicsDI on Schema.org https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.omicsdi.org%2Fdataset%2Fpride%2FPXD015689

![Screen Shot 2021-02-18 at 11 28 42](https://user-images.githubusercontent.com/52113/108350869-a6cb0980-71dc-11eb-9141-fc4b58bad404.png)

**Comment by shabai517** [comment]
Fixed already.
