### ISSUE TITLE
Error to request dataset 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#249]
When you click the request button nothing happen. 
  
![Screen Shot 2021-02-18 at 11 42 56](https://user-images.githubusercontent.com/52113/108352371-a7649f80-71de-11eb-8fe2-c64e070fd7ca.png)

**Comment by ypriverol** [comment]
https://www.ebi.ac.uk/pride/archive/projects/PXD023650/publish?r=other

**Comment by shabai517** [comment]
Fixed Already. Need more test if necessary.
