### ISSUE TITLE
Add a licence page for PRIDE

### ISSUE THREAD

**Issue by javizca** [PRIDE-Archive/pride-web#263]
https://www.ebi.ac.uk/pride/license

All EBI resources need to have a specific page devoted to their license details.

The text probably can be iteratively refined, but a first version can be found at:
https://docs.google.com/document/d/1LJ1KuGBw7XyIiR1yBaVyDJQyJKJe8cCCqY_ZpTN9xAQ/edit# 

Any comments welcome in that document

I have not included there on purpose the libraries, but it is something that could be added as well. As I said this  can be done in an iterative manner

**Comment by ypriverol** [comment]
This has been done in the recent release. Check one dataset: 

- https://www.ebi.ac.uk/pride/archive/projects/PXD033340
- License page: https://www.ebi.ac.uk/pride/markdownpage/license
