### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-web#274]
Once you click the link it shows 404 error - 
![Screenshot 2022-06-13 at 14 17 26](https://user-images.githubusercontent.com/38948179/173362905-c37438b5-fdc7-4252-a054-a97a430dd118.png)
![Screenshot 2022-06-13 at 14 17 36](https://user-images.githubusercontent.com/38948179/173362913-3e94e3c0-dcc9-4942-8469-d215dc986a92.png)

**Comment by orillusion-admin** [comment]
Fixed

**Comment by ypriverol** [comment]
This has been fixed.
