### ISSUE TITLE
Not able to download data via ascp (Aspera) anymore

### ISSUE THREAD

**Issue by bathy** [PRIDE-Archive/pride-web#277]
I used to use the following command to download data, but it doesn't work anymore, what is the change?

./ascp -TQ --overwrite=diff -k2 -P 33001 -N "*\.raw" -E "*\.*" -i ../etc/asperaw
eb_id_dsa.openssh pride_drop_006@hx-fasp-1.ebi.ac.uk:pride/data/archive/2020/01/PXD016632 ~/

**Comment by bathy** [comment]
Any update? @selvaebi

**Comment by ypriverol** [comment]
This has been updated in the present version.
