### ISSUE TITLE
Add Submission counts per Category

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#29]
We need to add the Submission per categories statistics to be shown in the web. 

Organism -> Organism Part -> DIseases -> Modification.

**Comment by ypriverol** [comment]
Waiting for this issue: https://github.com/PRIDE-Archive/pride-archive-pipelines/issues/1

**Comment by ypriverol** [comment]
The pipeline for Submissions per categories is done. The api call is here: http://ves-pg-41:9020/stats/SUBMISSIONS_PER_CATEGORIES

**Comment by shabai517** [comment]
Done. Please check @ypriverol
