### ISSUE TITLE
Error in visualizations for all the datasets

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#312]
@shabai517 : 

Bai can you remove this error for all the datasets, if you check the API for visualizations and it is down please do not show any errrors. 
![Screenshot 2023-10-04 at 06 47 20](https://github.com/PRIDE-Archive/pride-web/assets/52113/ce813af0-dec0-4a50-b463-659fa2fb9d7f)

**Comment by shabai517** [comment]
fixed with help of Suresh.
