### ISSUE TITLE
First iteration of crosslinking resource webpage 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#327]
Firstly, @shabai517 thanks a lot for the first iteration of the web page. Here are some of the initial comments from my side and priorities: 

**High-priority issues**: 

- [x] Rename "Xiview Data List" to "List of datasets" in Main table (which is the PRIDE Archive also has)
- [x] Rename "Xiview Data Details" to "Project Details" (which is the PRIDE Archive also has)
- [x] Add Organism to the detail page. 
- [x] The protein table header should be renamed from "Data Details" -> "Protein Details"
- [x] Link to PDB for every protein is -> https://www.ebi.ac.uk/pdbe/pdbe-kb/proteins/{protein accession}, example https://www.ebi.ac.uk/pdbe/pdbe-kb/proteins/P0ADC1. 
- [x] Link to the project in the Xiview (main table) -> https://www.ebi.ac.uk/pride/archive/xiview/network.html?project=PXD036833 
- [x] For that Link in the project we should use an icon as @sureshhewabi implemented before in https://www.ebi.ac.uk/pride/archive/xiview/
- [x] The title in the main table should be aligned to the left. 
- [x] The second table with the protein details should be paginated, which is more important than the first table now because it sometimes has more than 100 proteins. 
- [x] I'm surprised that the accession of the proteins in the second table sometimes is truncated when you have plenty of empty spaces in the table. This needs to be changed. 
- [x] If datasets are available by default we should have selected the first datasets making possible to show by default the second panel. 
- [x] Statistics plots.  

**Medium priority**: 

- [x] @sureshhewabi probably would be nice to get the protein name from UniProt, this is as far as I know a simple query to UniProt API and get the description, see here an example (https://rest.uniprot.org/uniprotkb/search?query=accession:P0ADC1%20OR%20accession:P10160&fields=protein_name). We should be able to show this protein name for each protein. 
- [x] Peptides, Proteins and spectra columns must be able to sort. 
- Add a search bar to search a protein accession in the detail page

**Comment by sureshhewabi** [comment]
**High priority:**

- [ ] Project Details-> Description field font size is 14 and 12 elsewhere.
- [ ] Add protein name and gene name to the detail table

**Medium priority:**
- [ ] List of datasets -> link -> This icon is great, but it don't obvious for the user that is a button. If you can put a button with the teal color and have the chart icon as the icon for the button, it will look great
- [ ] Default page size 10
- [ ] When user select a perticular dataset to see the detail view, it is better if you can automatically scroll to the detail section. Otherwise imagine if your use 40 pagination and click a record; user will not realise that the details has been populated for the selected dataset

**Comment by ypriverol** [comment]
statistics plots: 
- Peptides per ptoein -> https://www.ebi.ac.uk/pride/archive/xiview/ws/peptide-per-protein 

@shabai517 it could be a plot like: 
![Screenshot 2023-12-02 at 10 21 14](https://github.com/PRIDE-Archive/pride-web/assets/52113/f9fdf610-07ee-42f3-99c4-cb6c205ad647)

**Comment by ypriverol** [comment]
The button from PDB and AlphaFould should be smarter to know if the protein is present or not in those databases: 

- [ ] We need to add apart from the PDB button in the Protein table the link to AlphaFoldDB (e.g. https://alphafold.ebi.ac.uk/entry/G1SSJ7)
- [ ] In order to do it, we need to check both databases in the pipeline and have two boolean fields `inPDBeKB` `inAlphaFoldDB`. 
   - [ ] To check if the protein is in AlphaFoldDB please check the API (e.g. https://alphafold.ebi.ac.uk/api/prediction/G1SSJ7).
   - [ ] To check if the protein is in PDBe-KB please check the API (e.g. https://www.ebi.ac.uk/pdbe/graph-api/uniprot/G1SSJ7)

**Comment by ypriverol** [comment]
This is done.
