### ISSUE TITLE
Small issues with the crosslinking data. 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#337]
- [x] Sort projects by Accessions, this needs to be done with a sort by in the backend, original issue from @javizca (Is there an order in the listing of the datasets? This is a minor comment but maybe it would be good to list them based on the accession number (most recent at the top).
- [x] Search datasets in the dataset table and protein tables should be implemented. 
- [x] title of the dataset should not separate words between two lines, it should separate in spaces. 
- [x] Accessions in the dataset table should link back to the PRIDE Archive. 
- [x] Fix the visualization endpoint for each independent dataset in PRIDE, API endpoint broken (e.g. https://www.ebi.ac.uk/pride/archive/xiview/visualisations?pxid=PXD038060)
- [x] Publication Pubmed ID in the table and also in the description with the corresponding link to EuroPMC. 
- [x] Check the consistency of the data, for example (PXD038060 - 21 proteins, 2950 peptides, 1663 spectra. However in xiVIEW, at the top it says 19 proteins. Not consistent.)
- [x] Review the donut plot it gets cut in some resolutions the plot.

**Comment by colin-combe** [comment]
> Check the consistency of the data, for example (PXD038060 - 21 proteins, 2950 peptides, 1663 spectra. However in xiVIEW, at the top it says 19 proteins. Not consistent.)

That's because xiVIEW is, by default, not displaying the ambiguous (peptide position) links. I you click 'Ambig' in the filter at the bottom the numbers will match up. So this is something to be fixed in the xiVIEW javascript (by showing everything by default).

**Comment by colin-combe** [comment]
>  Fix the visualization endpoint for each independent dataset in PRIDE, API endpoint broken (e.g. https://www.ebi.ac.uk/pride/archive/xiview/visualisations?pxid=PXD038060)

I think you're using the wrong URL - show be https://www.ebi.ac.uk/pride/archive/xiview/network.html?project=PXD038060

**Comment by ypriverol** [comment]
> > Fix the visualization endpoint for each independent dataset in PRIDE, API endpoint broken (e.g. https://www.ebi.ac.uk/pride/archive/xiview/visualisations?pxid=PXD038060)
> 
> I think you're using the wrong URL - show be https://www.ebi.ac.uk/pride/archive/xiview/network.html?project=PXD038060

This is related with the previous way of getting the visualization urls for every file. @colin-combe we used to have that endpoint in the API. We will discuss in details all the issues after the Demo today and the collection of all the issues.

**Comment by colin-combe** [comment]
>  Check the consistency of the data, for example (PXD038060 - 21 proteins, 2950 peptides, 1663 spectra. However in xiVIEW, at the top it says 19 proteins. Not consistent.)

Should be fixed and deploy itself if i merge https://github.com/Rappsilber-Laboratory/xiview-server/pull/54 - I'll do that?
