### ISSUE TITLE
Autocomplete is ready to be included in the Web. 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#36]
@shabai517, Avinash has implemented the autocomplete function in the API http://ves-pg-41:9020/search/autocomplete?keyword=brain%20prot this will be great to recommend to the user when they are searching in the archive.

**Comment by shabai517** [comment]
Finished. Please check

**Comment by ypriverol** [comment]
Already tested. Well done @shabai517 .
