### ISSUE TITLE
The plot names should be changed 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#45]
The plot names should be changed in the current web (see attached image
![screen shot 2018-09-12 at 09 38 57](https://user-images.githubusercontent.com/52113/45413004-ff8f3300-b66f-11e8-9971-4a47111c6bf7.png)
): 

- Facets -> Submission Properties 
- Submission -> Public Submissions per year 
- Distribution -> Submissions per country

**Comment by ypriverol** [comment]
Done

**Comment by javizca** [comment]
Instead of "submissions" I would use the term "Submitted datasets", which is much more specific

**Comment by ypriverol** [comment]
Done
