### ISSUE TITLE
Home page 2nd graph Title: second word should be in lowercase

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-web#50]
![screen shot 2018-09-18 at 10 37 32](https://user-images.githubusercontent.com/5387193/45678980-855b2480-bb2f-11e8-9dd9-212c7b66e309.png)

**Comment by javizca** [comment]
yes

**Comment by ypriverol** [comment]
Juan, sorry. We haven’t open the test for other members of them rather than the development team. We are still capturing simple errors. We will open it soon.

**Comment by sureshhewabi** [comment]
I personally prefer to have those headings shorter and consistent, something like:

- Submissions by properties

- Submissions by time

- Submissions by countries
