### ISSUE TITLE
Autofiltering error in Search

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-web#51]
![screen shot 2018-09-18 at 10 46 48](https://user-images.githubusercontent.com/5387193/45679433-8e98c100-bb30-11e8-9611-f96785217a3c.png)

**Comment by ypriverol** [comment]
This error is related with API not the web.

**Comment by avinash-dev** [comment]
Fixed it in the API and deployed to wwwdev

**Comment by ypriverol** [comment]
that is why I can't reproduce the error. Thanks a lot.
