### ISSUE TITLE
Most of the links cannot be right click - it has the behaviour of left click

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-web#53]
For example, if you right click on a search results link, then it will open the page in the same tab. I found the same issue in home page links as well. It would be nice to fix

![screen shot 2018-09-18 at 10 57 40](https://user-images.githubusercontent.com/5387193/45680171-264adf00-bb32-11e8-8cea-9aac0fdcb3a9.png)

**Comment by ypriverol** [comment]
Would be nice but this is a single page app.
