### ISSUE TITLE
URL redirecting to FTP

### ISSUE THREAD

**Issue by avinash-dev** [PRIDE-Archive/pride-web#56]
On clicking a project title in the search results of Archive, we goto this page
http://wwwdev.ebi.ac.uk/pride/dataset/PXD000789
It gives additional information of a project.
But on refreshing the page it redirects to
http://ftp.pride.ebi.ac.uk/pride/dataset/PXD000789
And we get 404

**Comment by ypriverol** [comment]
Solved.
