### ISSUE TITLE
Documentation formatting issue 

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-web#57]
Example:

New line characters:
![screen shot 2018-09-18 at 11 19 20](https://user-images.githubusercontent.com/5387193/45681202-d02b6b00-bb34-11e8-9be3-4a3c3fca9f98.png)

Link is not working

![screen shot 2018-09-18 at 11 22 06](https://user-images.githubusercontent.com/5387193/45681341-2e584e00-bb35-11e8-9d5c-9e42647a1ad5.png)

**Comment by ypriverol** [comment]
Problem solve in the current implementation. Thanks, @sureshhewabi for reporting this.
