### ISSUE TITLE
Multiple bugs in the search results. 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#86]
We have multiple bugs in the Search results when searching for http://ves-hx-43:8083/pride/archive?keyword=PXD001539&sortConditions=accession&page=0&pageSize=20

- [ ] This query should give us one record, instead is given us all PRIDE records. The search is not working properly. Can you have a look @shabai517

- [ ] The properties in each card of the search is showing brackets `{ } ` (see picture Species section). 

<img width="994" alt="Screen Shot 2019-03-15 at 10 08 35" src="https://user-images.githubusercontent.com/52113/54424241-5dc5cd00-470a-11e9-87f4-4196edd7d169.png">

**Comment by avinash-dev** [comment]
I have checked the request in network console. The wrong API is being hit for search.
Here is an example of the correct api call
https://www.ebi.ac.uk/pride/ws/archive/v2/**search/**projects?keyword=PXD005011&pageSize=100&dateGap=%2B1YEAR&sortDirection=DESC&sortFields=submission_date

**Comment by shabai517** [comment]
fixed
