### ISSUE TITLE
Web page search issue

### ISSUE THREAD

**Issue by deeptijk** [PRIDE-Archive/pride-web#88]
Clicking on the Search button takes you out of the annotation page, rather taking you to archive directly. On the other hand if you just click any of the project mentioned in the first page takes you to step 2 (check). But if you click to next page and then click any one of the project gain it leads you to Archive. 

so only first page -> Mentioned projects can take you to next step, anything else leading you to archive.

But if you just type your required project in the address bar, it works. for example, 
 -- I searched PXD006550, first it says no match found but eventually gives the project on the page. Once you click the page it takes you to archive rather taking you to next level which is Check.
--- I just pasted it into address bar of the annotation system like this -  http://ves-hx-43:8083/pride/annotation/PXD006550/check, then it worked.

**Comment by shabai517** [comment]
fixed
