### ISSUE TITLE
It will be great to have an import from excel/csv file

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-web#90]
@David, @J-Andy and @deeptijk have recommended the import of the experimental design from an excel/csv file. Before starting that interface we need to agree on a standard way to define the csv. 

Preconditions: 

- Definition of a standard csv/excel file (Yasset)

We can add a simple button in the first screen of the experimental design `Import CSV` that contains the definition.

**Comment by J-Andy** [comment]
Here is an example of an experimental design file I use in my analysis. 1st column contains raw file name, 2nd column the fraction number in this analysis, 3rd column is the name I assign to the raw file (effectively sample name).   
[experimentalDesignTemplate.txt](https://github.com/PRIDE-Archive/pride-web/files/3131728/experimentalDesignTemplate.txt)
